# Generated by Django 5.2.9 on 2025-12-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbs',
            name='wbs_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
