# Generated by Django 5.2.9 on 2025-12-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaveraImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='primavera_imports/')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
