# Generated by Django 5.2.9 on 2025-12-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0002_primaveraimportfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
