# Generated by Django 5.2.9 on 2025-12-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0002_allowedextensions_primaveraimportfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="original_duration",
        ),
        migrations.AlterField(
            model_name="task",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
