# Generated by Django 5.2.9 on 2025-12-24 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "business_app",
            "0003_remove_task_original_duration_alter_task_end_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="delete_record_flag",
            field=models.BooleanField(default=False, verbose_name="Delete This Row"),
        ),
        migrations.AlterField(
            model_name="task",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="(*)Finish"),
        ),
        migrations.AlterField(
            model_name="task",
            name="remain_drtn_hr_cnt",
            field=models.IntegerField(verbose_name="Remaining Duration(d)"),
        ),
        migrations.AlterField(
            model_name="task",
            name="resources",
            field=models.ManyToManyField(
                through="business_app.TaskResource",
                to="business_app.resource",
                verbose_name="(*)Resources",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="(*)Start"),
        ),
        migrations.AlterField(
            model_name="task",
            name="status_code",
            field=models.CharField(max_length=50, verbose_name="Activity Status"),
        ),
        migrations.AlterField(
            model_name="task",
            name="target_cost",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                verbose_name="(*)Budgeted Total Cost($)",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="target_drtn_hr_cnt",
            field=models.IntegerField(verbose_name="Original Duration(d)"),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_code",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Activity ID"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_name",
            field=models.TextField(verbose_name="Activity Name"),
        ),
        migrations.AlterField(
            model_name="task",
            name="total_float_hr_cnt",
            field=models.IntegerField(verbose_name="(*)Total Float(d)"),
        ),
        migrations.AlterField(
            model_name="task",
            name="wbs",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="business_app.wbs",
                verbose_name="WBS Code",
            ),
        ),
    ]
