# Generated by Django 5.2.9 on 2025-12-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0003_alert_deleted_alert_deleted_by_cascade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="internal_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P", "Planned"),
                    ("H", "Hold"),
                    ("B", "Backlog"),
                    ("I", "In progress"),
                    ("C", "Completed"),
                    ("N", "Not started"),
                ],
                max_length=1,
                null=True,
                verbose_name="internal status",
            ),
        ),
    ]
