# Generated by Django 5.2.9 on 2025-12-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0004_alter_task_internal_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="kind",
            field=models.CharField(
                choices=[("I", "Information"), ("W", "Warning"), ("C", "Critical")],
                default="W",
                max_length=1,
                verbose_name="Alert type",
            ),
        ),
    ]
