# Generated by Django 5.2.9 on 2025-12-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0004_task_deleted_task_deleted_by_cascade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="act_end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Actual Finish"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="act_start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Actual Start"
            ),
        ),
    ]
