# Generated by Django 5.2.9 on 2025-12-26 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0005_task_act_end_date_task_act_start_date'),
        ('users_app', '0002_create_default_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='internal_status',
            field=models.CharField(blank=True, choices=[('P', 'planned'), ('S', 'started'), ('C', 'completed'), ('H', 'on hold')], max_length=1, null=True, verbose_name='internal status'),
        ),
        migrations.AddField(
            model_name='task',
            name='percent_complete',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='percent complete'),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Planned Date'),
        ),
        migrations.AddField(
            model_name='task',
            name='responsibles',
            field=models.ManyToManyField(blank=True, to='users_app.systemuser', verbose_name='Responsible User(s)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_cost',
            field=models.FloatField(verbose_name='(*)Budgeted Total Cost($)'),
        ),
    ]
