# Generated by Django 5.2.9 on 2026-01-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0006_alter_task_internal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('W', 'Warning'), ('C', 'Critical')], default='W', max_length=1, verbose_name='Alert type'),
        ),
    ]
