# Generated by Django 5.2.9 on 2026-01-03 22:10

from django.db import migrations
def remove_information_alerts(apps, schema_editor):
    Alert = apps.get_model("business_app", "Alert")
    Alert.objects.filter(kind="I").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0007_alter_alert_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='description',
        ),
        migrations.RunPython(
            remove_information_alerts, migrations.RunPython.noop
        ),
    ]
