# Generated by Django 5.2.9 on 2025-12-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0008_alert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wbs",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
