# Generated by Django 5.2.9 on 2026-01-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0009_alert_motive_alert_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="fuel_spent_by_hour",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="resource",
            name="rent_cost_by_hour_in_euros",
            field=models.FloatField(default=0),
        ),
    ]
