# Generated by Django 5.2.9 on 2025-12-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0009_alter_wbs_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="internal_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P", "Planned"),
                    ("I", "In progress"),
                    ("C", "Completed"),
                    ("N", "Not started"),
                    ("H", "Hold"),
                ],
                max_length=1,
                null=True,
                verbose_name="internal status",
            ),
        ),
    ]
