# Generated by Django 5.2.9 on 2025-12-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0010_alter_task_internal_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='percent_complete',
            new_name='internal_percent_complete',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='planned_date',
            new_name='internal_planned_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='responsibles',
            new_name='internal_responsibles',
        ),
        migrations.AlterField(
            model_name='task',
            name='internal_status',
            field=models.CharField(blank=True, choices=[('P', 'Planned'), ('H', 'Hold'), ('I', 'In progress'), ('C', 'Completed'), ('N', 'Not started')], max_length=1, null=True, verbose_name='internal status'),
        ),
    ]
