# Generated by Django 5.2.9 on 2026-01-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0010_resource_fuel_spent_by_hour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
