# Generated by Django 5.2.9 on 2025-12-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('business_app', '0011_rename_percent_complete_task_internal_percent_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='internal_responsibles',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='Responsible Roles(s)'),
        ),
    ]
