# Generated by Django 5.2.9 on 2026-01-10 04:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0012_alter_resource_resource_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="internal_percent_complete",
        ),
    ]
