# Generated by Django 5.2.9 on 2026-01-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0014_alter_task_internal_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="processed_area_by_hour",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="resource",
            name="processed_volume_by_hour",
            field=models.FloatField(default=0),
        ),
    ]
