# Generated by Django 5.2.9 on 2026-01-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0016_resourceowner_resource_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="identification",
            field=models.CharField(blank=True, null=True),
        ),
    ]
