# Generated by Django 5.2.9 on 2026-01-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0017_resource_identification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
